import { type ITheme } from "@xterm/xterm";
import type { BuiltInThemeId, EditorSettings } from "../../../../shared/settings";
import { editorFontStack } from "../../../shared/lib/fonts";
import { type ResolvedThemeTokens } from "../../../shared/lib/themeTokens";

const terminalThemes: Record<BuiltInThemeId, ITheme> = {
  "axon-dark": {
    background: "#0e1018",
    foreground: "#c8d0e0",
    cursor: "#80c8e0",
    cursorAccent: "#0e1018",
    selectionBackground: "#1e243080",
    black: "#0a0c12",
    brightBlack: "#364050",
    red: "#d0909c",
    brightRed: "#d0909c",
    green: "#90c8a0",
    brightGreen: "#90c8a0",
    yellow: "#d4b878",
    brightYellow: "#d4b878",
    blue: "#b0a0d8",
    brightBlue: "#b0a0d8",
    magenta: "#d0a888",
    brightMagenta: "#d0a888",
    cyan: "#80c8e0",
    brightCyan: "#80c8e0",
    white: "#c8d0e0",
    brightWhite: "#dce4f0",
  },
  sora: {
    background: "#10131a",
    foreground: "#d4dae7",
    cursor: "#7cc7d8",
    cursorAccent: "#10131a",
    selectionBackground: "#28304488",
    black: "#0a0d12",
    brightBlack: "#4b5565",
    red: "#f08c92",
    brightRed: "#ffadb1",
    green: "#8bd49c",
    brightGreen: "#a6e3b4",
    yellow: "#e5c07b",
    brightYellow: "#f2d69b",
    blue: "#8fb7ff",
    brightBlue: "#abc8ff",
    magenta: "#d7a3ff",
    brightMagenta: "#e4bdff",
    cyan: "#7cc7d8",
    brightCyan: "#9ee0ec",
    white: "#d4dae7",
    brightWhite: "#f0f4fb",
  },
  "catppuccin-mocha": {
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    cursor: "#f5e0dc",
    cursorAccent: "#1e1e2e",
    selectionBackground: "#585b7088",
    black: "#11111b",
    brightBlack: "#585b70",
    red: "#f38ba8",
    brightRed: "#f38ba8",
    green: "#a6e3a1",
    brightGreen: "#a6e3a1",
    yellow: "#f9e2af",
    brightYellow: "#f9e2af",
    blue: "#89b4fa",
    brightBlue: "#89b4fa",
    magenta: "#cba6f7",
    brightMagenta: "#cba6f7",
    cyan: "#94e2d5",
    brightCyan: "#94e2d5",
    white: "#cdd6f4",
    brightWhite: "#f5e0dc",
  },
  "zed-dark": {
    background: "#111316",
    foreground: "#d6d9df",
    cursor: "#7cc7e8",
    cursorAccent: "#111316",
    selectionBackground: "#2f3a4588",
    black: "#0d0f12",
    brightBlack: "#4d5562",
    red: "#ff9aa2",
    brightRed: "#ffb2b8",
    green: "#9fd68b",
    brightGreen: "#b7e8a6",
    yellow: "#e7c07a",
    brightYellow: "#f3d394",
    blue: "#7cc7e8",
    brightBlue: "#99d7f2",
    magenta: "#d7b7ff",
    brightMagenta: "#e2c8ff",
    cyan: "#72d0c9",
    brightCyan: "#95e3dd",
    white: "#d6d9df",
    brightWhite: "#f3f5f8",
  },
  "ayu-dark": {
    background: "#0d1016",
    foreground: "#bfbdb6",
    cursor: "#5ac1fe",
    cursorAccent: "#0d1016",
    selectionBackground: "#5ac1fe3d",
    black: "#0d1016",
    brightBlack: "#545557",
    red: "#ef7177",
    brightRed: "#83353b",
    green: "#aad84c",
    brightGreen: "#567627",
    yellow: "#feb454",
    brightYellow: "#92582b",
    blue: "#5ac1fe",
    brightBlue: "#27618c",
    magenta: "#39bae5",
    brightMagenta: "#205a78",
    cyan: "#95e5cb",
    brightCyan: "#4c806f",
    white: "#bfbdb6",
    brightWhite: "#bfbdb6",
  },
  "ayu-light": {
    background: "#fcfcfc",
    foreground: "#5c6166",
    cursor: "#3b9ee5",
    cursorAccent: "#fcfcfc",
    selectionBackground: "#3b9ee53d",
    black: "#fcfcfc",
    brightBlack: "#bcbec0",
    red: "#ef7271",
    brightRed: "#febab6",
    green: "#85b304",
    brightGreen: "#c7d98f",
    yellow: "#f1ad49",
    brightYellow: "#fed5a3",
    blue: "#3b9ee5",
    brightBlue: "#abcdf2",
    magenta: "#55b4d3",
    brightMagenta: "#b1d8e8",
    cyan: "#4dbf99",
    brightCyan: "#ace0cb",
    white: "#5c6166",
    brightWhite: "#5c6166",
  },
  "ayu-mirage": {
    background: "#242835",
    foreground: "#cccac2",
    cursor: "#72cffe",
    cursorAccent: "#242835",
    selectionBackground: "#72cffe3d",
    black: "#242835",
    brightBlack: "#67696e",
    red: "#f18779",
    brightRed: "#833f3c",
    green: "#d5fe80",
    brightGreen: "#75993c",
    yellow: "#fecf72",
    brightYellow: "#937237",
    blue: "#72cffe",
    brightBlue: "#336d8d",
    magenta: "#5bcde5",
    brightMagenta: "#2b6c7b",
    cyan: "#95e6cb",
    brightCyan: "#4c806f",
    white: "#cccac2",
    brightWhite: "#cccac2",
  },
};

export function getTerminalOptions(
  editorSettings: EditorSettings,
  themeTokens: ResolvedThemeTokens,
) {
  // The xterm palette is derived from the active Axon theme, but the terminal
  // background/foreground tokens still win at the end. That lets theme authors
  // tune the shell surface without duplicating every ANSI color entry.
  const theme = terminalThemes[editorSettings.themeId as BuiltInThemeId] ??
    terminalThemes["axon-dark"];

  return {
    theme: {
      ...theme,
      background: themeTokens["terminal.background"],
      foreground: themeTokens["terminal.foreground"],
    },
    fontFamily: editorFontStack(editorSettings.fontFamily),
    fontWeight: editorSettings.fontWeight,
    fontSize: Math.max(10, editorSettings.fontSize - 1),
    lineHeight: Math.max(
      1,
      editorSettings.lineHeight / editorSettings.fontSize,
    ),
  };
}
