version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Africa/Accra
    open-pull-requests-limit: 10
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /services/core
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Africa/Accra
    open-pull-requests-limit: 10
    groups:
      go-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Africa/Accra
    open-pull-requests-limit: 10
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
