const FALLBACK_FILE_ICON = "_file.svg";
const FALLBACK_FOLDER_ICON = "_folder.svg";
const FALLBACK_FOLDER_OPEN_ICON = "_folder_open.svg";

const fileExtensionMap: Record<string, string> = {
  "3d": "3d.svg",
  abap: "_file.svg",
  ai: "adobe-ai.svg",
  aiff: "audio.svg",
  android: "android.svg",
  apib: "api-blueprint.svg",
  apex: "_file.svg",
  applescript: "apple.svg",
  ard: "arduino.svg",
  arduino: "arduino.svg",
  asc: "asciidoc.svg",
  asciidoc: "asciidoc.svg",
  asm: "assembly.svg",
  astro: "astro.svg",
  audio: "audio.svg",
  avif: "image.svg",
  ahk: "autohotkey.svg",
  bat: "batch.svg",
  bash: "bash.svg",
  bazel: "bazel.svg",
  bicep: "bicep.svg",
  bin: "binary.svg",
  biome: "biome.svg",
  bmp: "image.svg",
  bower: "bower.svg",
  browserslistrc: "browserslist.svg",
  bun: "bun.svg",
  cabal: "cabal.svg",
  c: "c.svg",
  h: "c-header.svg",
  cert: "certificate.svg",
  cer: "certificate.svg",
  pem: "certificate.svg",
  changelog: "changelog.svg",
  clj: "clojure.svg",
  cljs: "clojure.svg",
  cljc: "clojure.svg",
  cmake: "cmake.svg",
  cob: "cobol.svg",
  cobol: "cobol.svg",
  coffee: "coffeescript.svg",
  config: "config.svg",
  conf: "config.svg",
  cpp: "cpp.svg",
  cc: "cpp.svg",
  cxx: "cpp.svg",
  cplusplus: "cpp.svg",
  hpp: "cpp-header.svg",
  hh: "cpp-header.svg",
  hxx: "cpp-header.svg",
  cr: "crystal.svg",
  cs: "csharp.svg",
  css: "css.svg",
  cssmap: "css-map.svg",
  csv: "csv.svg",
  cu: "cuda.svg",
  cue: "cue.svg",
  cypress: "cypress.svg",
  d: "d.svg",
  dart: "dart.svg",
  db: "database.svg",
  sqlite: "database.svg",
  sqlite3: "database.svg",
  diff: "diff.svg",
  patch: "diff.svg",
  dockerfile: "docker.svg",
  drawio: "drawio.svg",
  dtd: "xml.svg",
  eex: "elixir.svg",
  ejs: "ejs.svg",
  ex: "elixir.svg",
  exs: "elixir.svg",
  elm: "elm.svg",
  env: "env.svg",
  erl: "erlang.svg",
  hrl: "erlang.svg",
  exe: "exe.svg",
  fish: "bash.svg",
  fig: "figma.svg",
  figma: "figma.svg",
  firebase: "firebase.svg",
  fs: "fsharp.svg",
  fsx: "fsharp.svg",
  fsi: "fsharp.svg",
  fvm: "fvm.svg",
  gd: "godot.svg",
  gdshader: "godot-assets.svg",
  gif: "image.svg",
  gleam: "gleam.svg",
  gql: "graphql.svg",
  graphql: "graphql.svg",
  go: "go.svg",
  gotmpl: "go-template.svg",
  tmpl: "go-template.svg",
  gradle: "gradle.svg",
  groovy: "groovy.svg",
  gvy: "groovy.svg",
  haml: "haml.svg",
  hare: "hare.svg",
  hs: "haskell.svg",
  lhs: "haskell.svg",
  hcl: "opentofu.svg",
  heic: "image.svg",
  heif: "image.svg",
  helm: "helm.svg",
  htm: "html.svg",
  html: "html.svg",
  http: "http.svg",
  huff: "huff.svg",
  ico: "favicon.svg",
  icns: "image.svg",
  ini: "config.svg",
  jfif: "image.svg",
  java: "java.svg",
  jar: "java.svg",
  jpeg: "image.svg",
  jpg: "image.svg",
  jinja: "jinja.svg",
  jinja2: "jinja.svg",
  jl: "julia.svg",
  js: "javascript.svg",
  cjs: "javascript.svg",
  mjs: "javascript.svg",
  jsx: "javascript-react.svg",
  jsmap: "javascript-map.svg",
  json: "json.svg",
  jsonc: "json.svg",
  json5: "json.svg",
  jsonl: "json.svg",
  jsonschema: "json-schema.svg",
  kt: "kotlin.svg",
  kts: "kotlin.svg",
  less: "less.svg",
  lisp: "lisp.svg",
  cl: "lisp.svg",
  lock: "lock.svg",
  log: "log.svg",
  lua: "lua.svg",
  luau: "luau.svg",
  lune: "lua.svg",
  m: "c.svg",
  mm: "cpp.svg",
  makefile: "makefile.svg",
  marko: "marko.svg",
  markdown: "markdown.svg",
  md: "markdown.svg",
  mdx: "markdown-mdx.svg",
  mjsmap: "javascript-map.svg",
  mjml: "mjml.svg",
  ml: "ocaml.svg",
  mli: "ocaml.svg",
  moon: "moonrepo.svg",
  ninja: "ninja.svg",
  nim: "nim.svg",
  nix: "nix.svg",
  odin: "odin.svg",
  pcss: "postcss.svg",
  pdf: "pdf.svg",
  perl: "perl.svg",
  pl: "perl.svg",
  pm: "perl.svg",
  php: "php.svg",
  php3: "php.svg",
  php4: "php.svg",
  php5: "php.svg",
  phtml: "php.svg",
  png: "image.svg",
  proto: "proto.svg",
  psb: "adobe-ps.svg",
  psd: "adobe-ps.svg",
  pug: "pug.svg",
  puppet: "puppet.svg",
  pp: "puppet.svg",
  py: "python.svg",
  pyc: "python-compiled.svg",
  pyo: "python-compiled.svg",
  qml: "_file.svg",
  qs: "_file.svg",
  r: "r.svg",
  rmd: "rmd.svg",
  rb: "ruby.svg",
  rbx: "ruby.svg",
  rake: "ruby.svg",
  gemspec: "ruby-gem.svg",
  reason: "reason.svg",
  raw: "image.svg",
  res: "rescript.svg",
  rei: "rescript.svg",
  rs: "rust.svg",
  rlib: "rust-alt.svg",
  sass: "sass.svg",
  scala: "scala.svg",
  sc: "scala.svg",
  scss: "sass.svg",
  sh: "bash.svg",
  shader: "shader.svg",
  sln: "msbuild.svg",
  sol: "solidity.svg",
  sql: "database.svg",
  sqlite2: "database.svg",
  svelte: "svelte.svg",
  swift: "swift.svg",
  svg: "svg.svg",
  tga: "image.svg",
  tif: "image.svg",
  tiff: "image.svg",
  tcl: "_file.svg",
  toml: "toml.svg",
  ts: "typescript.svg",
  mts: "typescript.svg",
  cts: "typescript.svg",
  tsx: "typescript-react.svg",
  dts: "typescript-def.svg",
  twig: "twig.svg",
  txt: "text.svg",
  vala: "vala.svg",
  vb: "visual-studio.svg",
  vbs: "visual-studio.svg",
  vue: "vue.svg",
  wasm: "binary.svg",
  wav: "audio.svg",
  webp: "image.svg",
  wgsl: "_file.svg",
  wxt: "wxt.svg",
  xml: "xml.svg",
  xsd: "xml.svg",
  xsl: "xml.svg",
  yaml: "yaml.svg",
  yml: "yaml.svg",
  zig: "zig.svg",
  zip: "zip.svg",
  zsh: "bash.svg",
};

const specialFilenameMap: Record<string, string> = {
  ".babelrc": "babel.svg",
  ".browserslistrc": "browserslist.svg",
  ".cursorrules": "cursor.svg",
  ".dockerignore": "docker-ignore.svg",
  ".editorconfig": "editorconfig.svg",
  ".env": "env.svg",
  ".envrc": "envrc.svg",
  ".eslintignore": "eslint-ignore.svg",
  ".eslintrc": "eslint.svg",
  ".firebaserc": "firebase.svg",
  ".gitignore": "git.svg",
  ".gitattributes": "git.svg",
  ".gitmodules": "git.svg",
  ".npmignore": "npm-ignore.svg",
  ".npmrc": "npm.svg",
  ".prettierignore": "prettier-ignore.svg",
  ".prettierrc": "prettier.svg",
  ".stylelintignore": "stylelint-ignore.svg",
  ".stylelintrc": "stylelint.svg",
  ".vercelignore": "vercel-ignore.svg",
  ".vscodeignore": "vscode-ignore.svg",
  "angular.json": "angular.svg",
  "ansible-lint.yml": "ansible-lint.svg",
  "app.config.ts": "nuxt.svg",
  "astro.config.js": "astro-config.svg",
  "astro.config.mjs": "astro-config.svg",
  "astro.config.ts": "astro-config.svg",
  "azure-pipelines.yml": "azure-pipelines.svg",
  "babel.config.js": "babel.svg",
  "babel.config.json": "babel.svg",
  "biome.json": "biome.svg",
  "bun.lock": "bun-lock.svg",
  "bun.lockb": "bun-lock.svg",
  "cargo.lock": "cargo-lock.svg",
  "cargo.toml": "cargo.svg",
  "cmakelists.txt": "cmake.svg",
  "code_of_conduct.md": "code-of-conduct.svg",
  "codeowners": "codeowners.svg",
  "commitlint.config.js": "commitlint.svg",
  "commitlint.config.ts": "commitlint.svg",
  "contributing.md": "contributing.svg",
  "deno.json": "deno.svg",
  "deno.jsonc": "deno.svg",
  "deno.lock": "deno_lock.svg",
  "docker-compose.yaml": "docker-compose.svg",
  "docker-compose.yml": "docker-compose.svg",
  "dockerfile": "docker.svg",
  "drizzle.config.ts": "drizzle-orm.svg",
  "eslint.config.js": "eslint.svg",
  "eslint.config.mjs": "eslint.svg",
  "eslint.config.ts": "eslint.svg",
  "firebase.json": "firebase.svg",
  "go.mod": "go.svg",
  "go.sum": "go.svg",
  "gradle.properties": "gradle.svg",
  "gulpfile.js": "gulp.svg",
  "hardhat.config.js": "hardhat.svg",
  "hardhat.config.ts": "hardhat.svg",
  "humans.txt": "humans.svg",
  "jsconfig.json": "javascript.svg",
  "justfile": "just.svg",
  "lerna.json": "lerna.svg",
  "license": "license.svg",
  "license.md": "license.svg",
  "license.txt": "license.svg",
  "makefile": "makefile.svg",
  "next.config.js": "next.svg",
  "next.config.mjs": "next.svg",
  "next.config.ts": "next.svg",
  "nginx.conf": "nginx.svg",
  "nodemon.json": "nodemon.svg",
  "nuxt.config.js": "nuxt.svg",
  "nuxt.config.ts": "nuxt.svg",
  "package-lock.json": "npm-lock.svg",
  "package.json": "package-json.svg",
  "pnpm-lock.yaml": "pnpm-lock.svg",
  "pnpm-workspace.yaml": "pnpm.svg",
  "postcss.config.js": "postcss.svg",
  "prettier.config.js": "prettier.svg",
  "prettier.config.mjs": "prettier.svg",
  "pyproject.toml": "python-config.svg",
  "README.md": "markdown.svg",
  "readme.md": "markdown.svg",
  "renovate.json": "renovate.svg",
  "requirements.txt": "python.svg",
  "rollup.config.js": "rollup.svg",
  "rollup.config.mjs": "rollup.svg",
  "rollup.config.ts": "rollup.svg",
  "rust-toolchain": "rust-alt.svg",
  "rust-toolchain.toml": "rust-alt.svg",
  "tailwind.config.js": "tailwind.svg",
  "tailwind.config.ts": "tailwind.svg",
  "tsconfig.json": "typescript.svg",
  "turbo.json": "turbo.svg",
  "vite.config.js": "vite.svg",
  "vite.config.mjs": "vite.svg",
  "vite.config.ts": "vite.svg",
  "vitest.config.js": "vitest.svg",
  "vitest.config.ts": "vitest.svg",
  "webpack.config.js": "webpack.svg",
  "webpack.config.ts": "webpack.svg",
  "wrangler.toml": "wrangler.svg",
  "xmake.lua": "xmake.svg",
  "yarn.lock": "yarn.svg",
};

const folderMap: Record<string, string> = {
  ".cursor": "folder_cursor",
  ".devcontainer": "folder_devcontainer",
  ".direnv": "folder_direnv",
  ".git": "folder_git",
  ".github": "folder_github",
  ".gitlab": "folder_gitlab",
  ".husky": "folder_husky",
  ".idea": "folder_intellij",
  ".turbo": "folder_turbo",
  ".vscode": "folder_vscode",
  android: "folder_android",
  api: "folder_api",
  apis: "folder_api",
  app: "folder_app",
  apps: "folder_app",
  assets: "folder_assets",
  audio: "folder_audio",
  audit: "folder_audit",
  aws: "folder_aws",
  benchmark: "folder_benchmark",
  benchmarks: "folder_benchmark",
  build: "folder_dist",
  caddy: "folder_caddy",
  cargo: "folder_cargo",
  client: "folder_client",
  cloud: "folder_cloud",
  command: "folder_command",
  commands: "folder_command",
  common: "folder_shared",
  components: "folder_components",
  composables: "folder_composables",
  config: "folder_config",
  configs: "folder_config",
  connection: "folder_connection",
  connections: "folder_connection",
  constants: "folder_constant",
  content: "folder_content",
  contents: "folder_content",
  controllers: "folder_controllers",
  core: "folder_core",
  coverage: "folder_coverage",
  cypress: "folder_cypress",
  database: "folder_database",
  databases: "folder_database",
  db: "folder_database",
  debug: "folder_debug",
  dist: "folder_dist",
  docker: "folder_docker",
  docs: "folder_docs",
  documentation: "folder_docs",
  downloads: "folder_download",
  drizzle: "folder_drizzle-orm",
  examples: "folder_examples",
  fastlane: "folder_fastlane",
  firebase: "folder_firebase",
  fonts: "folder_fonts",
  functions: "folder_functions",
  fvm: "folder_fvm",
  hooks: "folder_hooks",
  icon: "folder_images",
  icons: "folder_images",
  image: "folder_images",
  images: "folder_images",
  img: "folder_images",
  imgs: "folder_images",
  layouts: "folder_layouts",
  lib: "folder_lib",
  libs: "folder_lib",
  locales: "folder_locales",
  logs: "folder_debug",
  middleware: "folder_middleware",
  middlewares: "folder_middleware",
  media: "folder_assets",
  medias: "folder_assets",
  mocks: "folder_mocks",
  node_modules: "folder_node",
  packages: "folder_packages",
  pages: "folder_views",
  plugins: "folder_plugins",
  private: "folder_private",
  proto: "folder_proto",
  public: "folder_public",
  queue: "folder_queue",
  routes: "folder_routes",
  scripts: "folder_scripts",
  security: "folder_security",
  server: "folder_server",
  shared: "folder_shared",
  source: "folder_src",
  src: "folder_src",
  static: "folder_assets",
  picture: "folder_images",
  pictures: "folder_images",
  photo: "folder_images",
  photos: "folder_images",
  screenshot: "folder_images",
  screenshots: "folder_images",
  styles: "folder_styles",
  svg: "folder_svg",
  svgs: "folder_svg",
  templates: "folder_templates",
  temp: "folder_temp",
  tests: "folder_tests",
  themes: "folder_themes",
  tmp: "folder_temp",
  types: "folder_types",
  utils: "folder_utils",
  video: "folder_video",
  videos: "folder_video",
  views: "folder_views",
  windows: "folder_windows",
};

function withSvg(iconName: string) {
  return iconName.endsWith(".svg") ? iconName : `${iconName}.svg`;
}

function normalizeFilename(filename: string) {
  return filename.trim().toLowerCase();
}

function getExtension(filename: string) {
  const normalized = normalizeFilename(filename);
  const parts = normalized.split(".");
  return parts.length > 1 ? parts[parts.length - 1] : "";
}

function getFolderBaseIcon(name: string) {
  const normalized = normalizeFilename(name);
  return folderMap[normalized];
}

export function resolveFileIcon(filename: string) {
  const normalized = normalizeFilename(filename);
  const extension = getExtension(normalized);

  // The explicit family checks sit before exact filename checks because
  // environment variants are intentionally open-ended: `.env.local`,
  // `.env.production`, and `.env.test.local` should all share the same icon.
  // Without this rule, only `.env` would work and every real project variant
  // would fall back to the generic file icon.
  if (normalized === ".env" || normalized.startsWith(".env.")) {
    return "env.svg";
  }

  const exactIcon = specialFilenameMap[normalized];
  if (exactIcon) return exactIcon;

  const extensionIcon = fileExtensionMap[extension];
  if (extensionIcon) return extensionIcon;

  return FALLBACK_FILE_ICON;
}

export function resolveFolderIcon(name: string, expanded: boolean) {
  const baseIcon = getFolderBaseIcon(name);

  if (!baseIcon) {
    return expanded ? FALLBACK_FOLDER_OPEN_ICON : FALLBACK_FOLDER_ICON;
  }

  // Catppuccin ships folder icons as paired closed/open files. Keeping the
  // `_open` suffix rule in one resolver prevents the tree component from
  // needing to know about file naming conventions, and it avoids one-off bugs
  // where a new folder mapping only works for the closed state.
  return withSvg(expanded ? `${baseIcon}_open` : baseIcon);
}
