import { type ExtensionThemeSyntaxStyle } from "../../../shared/extensions";
import { createDefaultCaptureEntries } from "./captureRegistry";
import { type AxonThemeDefinition, type ThemeTokenMap } from "./types";

function createSyntax(tokens: ThemeTokenMap) {
  return Object.fromEntries(
    createDefaultCaptureEntries(tokens).map(([capture, style]) => [
      capture,
      {
        color: style.color,
        fontStyle: style.fontStyle,
      },
    ]),
  ) as Record<string, ExtensionThemeSyntaxStyle>;
}

const blackTokens: ThemeTokenMap = {
  background: "#000000",
  "status_bar.background": "#000000",
  "title_bar.background": "#000000",
  "toolbar.background": "#000000",
  "sidebar.background": "#000000",
  "sidebar.hover_background": "#151515",
  "sidebar.border": "#202020",
  "tab.active_background": "#101010",
  "panel.background": "#000000",
  "panel.border": "#202020",
  "panel.overlay_hover": "#151515",
  "editor.foreground": "#e8e8e8",
  "editor.background": "#000000",
  "editor.gutter.background": "#000000",
  "terminal.background": "#000000",
  "terminal.foreground": "#e8e8e8",
  "syntax.comment": "#767676",
  "syntax.keyword": "#67d8ef",
  "syntax.string": "#f08da8",
  "syntax.number": "#c9a7ff",
  "syntax.type": "#e6a96b",
  "syntax.function": "#e8c76a",
  "syntax.method": "#70d6c6",
  "syntax.class": "#f0ad72",
  "syntax.interface": "#e6a96b",
  "syntax.variable": "#e8e8e8",
  "syntax.parameter": "#d6b0ff",
  "syntax.property": "#9cdcfe",
  "syntax.constant": "#c9a7ff",
  "syntax.operator": "#f08da8",
  "syntax.bracket": "#a8a8a8",
  "syntax.import": "#67d8ef",
  "syntax.tag": "#67d8ef",
  "syntax.attribute": "#e8c76a",
};

const whiteTokens: ThemeTokenMap = {
  background: "#ffffff",
  "status_bar.background": "#ffffff",
  "title_bar.background": "#ffffff",
  "toolbar.background": "#ffffff",
  "sidebar.background": "#ffffff",
  "sidebar.hover_background": "#f1f1f1",
  "sidebar.border": "#d4d4d4",
  "tab.active_background": "#f5f5f5",
  "panel.background": "#ffffff",
  "panel.border": "#d4d4d4",
  "panel.overlay_hover": "#f1f1f1",
  "editor.foreground": "#171717",
  "editor.background": "#ffffff",
  "editor.gutter.background": "#ffffff",
  "terminal.background": "#ffffff",
  "terminal.foreground": "#171717",
  "syntax.comment": "#666666",
  "syntax.keyword": "#743b94",
  "syntax.string": "#356b2f",
  "syntax.number": "#874812",
  "syntax.type": "#17686e",
  "syntax.function": "#005d8c",
  "syntax.method": "#14645d",
  "syntax.class": "#754900",
  "syntax.interface": "#315f67",
  "syntax.variable": "#171717",
  "syntax.parameter": "#773d00",
  "syntax.property": "#00596f",
  "syntax.constant": "#942d4c",
  "syntax.operator": "#5d456d",
  "syntax.bracket": "#565656",
  "syntax.import": "#743b94",
  "syntax.tag": "#176453",
  "syntax.attribute": "#705000",
};

export const axonBlackTheme: AxonThemeDefinition = {
  id: "axon-black",
  label: "Axon Black",
  base: "vs-dark",
  tokens: blackTokens,
  monacoColors: {
    "editor.lineHighlightBackground": "#0d0d0d",
    "editor.selectionBackground": "#264f7880",
    "editor.inactiveSelectionBackground": "#264f784d",
    "editor.findMatchBackground": "#5b4b1f",
    "editor.findMatchHighlightBackground": "#5b4b1f80",
    "editorLineNumber.foreground": "#505050",
    "editorLineNumber.activeForeground": "#d0d0d0",
    "editorCursor.foreground": "#ffffff",
    "editorIndentGuide.background1": "#242424",
    "editorIndentGuide.activeBackground1": "#5a5a5a",
    "editorBracketMatch.background": "#1d334080",
    "editorBracketMatch.border": "#67d8ef",
    "scrollbarSlider.background": "#5a5a5a55",
    "scrollbarSlider.hoverBackground": "#77777777",
    "scrollbarSlider.activeBackground": "#99999999",
    "editorWidget.background": "#080808",
    "editorWidget.border": "#1a1a1a",
    "editorSuggestWidget.background": "#080808",
    "editorSuggestWidget.border": "#1a1a1a",
    "editorSuggestWidget.selectedBackground": "#1b1b1b",
    "editorSuggestWidget.highlightForeground": "#67d8ef",
    focusBorder: "#67d8ef",
  },
  syntax: createSyntax(blackTokens),
};

export const axonWhiteTheme: AxonThemeDefinition = {
  id: "axon-white",
  label: "Axon White",
  base: "vs",
  tokens: whiteTokens,
  monacoColors: {
    "editor.lineHighlightBackground": "#f5f5f5",
    "editor.selectionBackground": "#add6ff99",
    "editor.inactiveSelectionBackground": "#add6ff66",
    "editor.findMatchBackground": "#f1c44f88",
    "editor.findMatchHighlightBackground": "#f1c44f55",
    "editorLineNumber.foreground": "#8a8a8a",
    "editorLineNumber.activeForeground": "#171717",
    "editorCursor.foreground": "#000000",
    "editorIndentGuide.background1": "#dedede",
    "editorIndentGuide.activeBackground1": "#8a8a8a",
    "editorBracketMatch.background": "#dceef5",
    "editorBracketMatch.border": "#005d8c",
    "scrollbarSlider.background": "#77777733",
    "scrollbarSlider.hoverBackground": "#66666655",
    "scrollbarSlider.activeBackground": "#55555577",
    "editorWidget.background": "#ffffff",
    "editorWidget.border": "#c8c8c8",
    "editorSuggestWidget.background": "#ffffff",
    "editorSuggestWidget.border": "#c8c8c8",
    "editorSuggestWidget.selectedBackground": "#e4f1f7",
    "editorSuggestWidget.highlightForeground": "#005d8c",
    focusBorder: "#005d8c",
  },
  syntax: createSyntax(whiteTokens),
};

export const axonMonochromeThemes = [axonBlackTheme, axonWhiteTheme];
