import { type AxonThemeDefinition, type ThemeTokenMap } from "./types";
import { ayuSyntaxByThemeId } from "./ayuSyntax";

function makeAyuTheme(input: {
  id: AxonThemeDefinition["id"];
  label: string;
  base: AxonThemeDefinition["base"];
  tokens: ThemeTokenMap;
  monacoColors: AxonThemeDefinition["monacoColors"];
  syntax?: AxonThemeDefinition["syntax"];
}): AxonThemeDefinition {
  return input;
}

export const ayuDarkTheme = makeAyuTheme({
  id: "ayu-dark",
  label: "Ayu Dark",
  base: "vs-dark",
  tokens: {
    background: "#313337ff",
    "status_bar.background": "#313337ff",
    "title_bar.background": "#313337ff",
    "toolbar.background": "#0d1016ff",
    "sidebar.background": "#1f2127ff",
    "sidebar.hover_background": "#2d2f34ff",
    "sidebar.border": "#2d2f34ff",
    "tab.active_background": "#0d1016ff",
    "panel.background": "#1f2127ff",
    "panel.border": "#2d2f34ff",
    "panel.overlay_hover": "#2d2f34ff",
    "editor.foreground": "#bfbdb6ff",
    "editor.background": "#0d1016ff",
    "editor.gutter.background": "#0d1016ff",
    "terminal.background": "#0d1016ff",
    "terminal.foreground": "#bfbdb6ff",
    "syntax.comment": "#abb5be8c",
    "syntax.keyword": "#ff8f3fff",
    "syntax.string": "#a9d94bff",
    "syntax.number": "#d2a6ffff",
    "syntax.type": "#59c2ffff",
    "syntax.function": "#ffb353ff",
    "syntax.method": "#ffb353ff",
    "syntax.class": "#5ac1feff",
    "syntax.interface": "#59c2ffff",
    "syntax.variable": "#bfbdb6ff",
    "syntax.parameter": "#bfbdb6ff",
    "syntax.property": "#5ac1feff",
    "syntax.constant": "#d2a6ffff",
    "syntax.operator": "#f29668ff",
    "syntax.bracket": "#a6a5a0ff",
    "syntax.import": "#ff8f3fff",
    "syntax.tag": "#5ac1feff",
    "syntax.attribute": "#5ac1feff",
  },
  syntax: ayuSyntaxByThemeId["ayu-dark"],
  monacoColors: {
    "editor.lineHighlightBackground": "#1f2127bf",
    "editor.selectionBackground": "#5ac1fe3d",
    "editor.inactiveSelectionBackground": "#5ac1fe1a",
    "editor.findMatchBackground": "#5ac2fe66",
    "editor.findMatchHighlightBackground": "#5ac2fe66",
    "editorLineNumber.foreground": "#bfbdb659",
    "editorLineNumber.activeForeground": "#bfbdb6ff",
    "editorCursor.foreground": "#5ac1feff",
    "editorIndentGuide.background1": "#bfbdb60d",
    "editorIndentGuide.activeBackground1": "#bfbdb61a",
    "editorBracketMatch.background": "#5ac1fe1a",
    "editorBracketMatch.border": "#5ac1feff",
    "scrollbarSlider.background": "#bfbdb64c",
    "scrollbarSlider.hoverBackground": "#2d2f34ff",
    "scrollbarSlider.activeBackground": "#3e4043ff",
    "editorWidget.background": "#1f2127ff",
    "editorWidget.border": "#2d2f34ff",
    "editorSuggestWidget.background": "#1f2127ff",
    "editorSuggestWidget.border": "#2d2f34ff",
    "editorSuggestWidget.selectedBackground": "#3e4043ff",
    "editorSuggestWidget.highlightForeground": "#5ac1feff",
    focusBorder: "#1b4a6eff",
  },
});

export const ayuLightTheme = makeAyuTheme({
  id: "ayu-light",
  label: "Ayu Light",
  base: "vs",
  tokens: {
    background: "#dcdddeff",
    "status_bar.background": "#dcdddeff",
    "title_bar.background": "#dcdddeff",
    "toolbar.background": "#fcfcfcff",
    "sidebar.background": "#ececedff",
    "sidebar.hover_background": "#d4d6d8ff",
    "sidebar.border": "#dfe0e1ff",
    "tab.active_background": "#fcfcfcff",
    "panel.background": "#ececedff",
    "panel.border": "#dfe0e1ff",
    "panel.overlay_hover": "#d4d6d8ff",
    "editor.foreground": "#5c6166ff",
    "editor.background": "#fcfcfcff",
    "editor.gutter.background": "#fcfcfcff",
    "terminal.background": "#fcfcfcff",
    "terminal.foreground": "#5c6166ff",
    "syntax.comment": "#787b8099",
    "syntax.keyword": "#fa8d3eff",
    "syntax.string": "#86b300ff",
    "syntax.number": "#a37accff",
    "syntax.type": "#389ee6ff",
    "syntax.function": "#f2ad48ff",
    "syntax.method": "#f2ad48ff",
    "syntax.class": "#3b9ee5ff",
    "syntax.interface": "#389ee6ff",
    "syntax.variable": "#5c6166ff",
    "syntax.parameter": "#5c6166ff",
    "syntax.property": "#3b9ee5ff",
    "syntax.constant": "#a37accff",
    "syntax.operator": "#ed9365ff",
    "syntax.bracket": "#73777bff",
    "syntax.import": "#fa8d3eff",
    "syntax.tag": "#3b9ee5ff",
    "syntax.attribute": "#3b9ee5ff",
  },
  syntax: ayuSyntaxByThemeId["ayu-light"],
  monacoColors: {
    "editor.lineHighlightBackground": "#ececedbf",
    "editor.selectionBackground": "#3b9ee53d",
    "editor.inactiveSelectionBackground": "#3b9ee51a",
    "editor.findMatchBackground": "#3b9ee566",
    "editor.findMatchHighlightBackground": "#3b9ee566",
    "editorLineNumber.foreground": "#5c616659",
    "editorLineNumber.activeForeground": "#5c6166ff",
    "editorCursor.foreground": "#3b9ee5ff",
    "editorIndentGuide.background1": "#5c61660d",
    "editorIndentGuide.activeBackground1": "#5c61661a",
    "editorBracketMatch.background": "#3b9ee51a",
    "editorBracketMatch.border": "#3b9ee5ff",
    "scrollbarSlider.background": "#5c61664c",
    "scrollbarSlider.hoverBackground": "#dfe0e1ff",
    "scrollbarSlider.activeBackground": "#cfd0d2ff",
    "editorWidget.background": "#ececedff",
    "editorWidget.border": "#dfe0e1ff",
    "editorSuggestWidget.background": "#ececedff",
    "editorSuggestWidget.border": "#dfe0e1ff",
    "editorSuggestWidget.selectedBackground": "#cfd0d2ff",
    "editorSuggestWidget.highlightForeground": "#3b9ee5ff",
    focusBorder: "#c4daf6ff",
  },
});

export const ayuMirageTheme = makeAyuTheme({
  id: "ayu-mirage",
  label: "Ayu Mirage",
  base: "vs-dark",
  tokens: {
    background: "#464a52ff",
    "status_bar.background": "#464a52ff",
    "title_bar.background": "#464a52ff",
    "toolbar.background": "#242835ff",
    "sidebar.background": "#353944ff",
    "sidebar.hover_background": "#43464fff",
    "sidebar.border": "#43464fff",
    "tab.active_background": "#242835ff",
    "panel.background": "#353944ff",
    "panel.border": "#43464fff",
    "panel.overlay_hover": "#43464fff",
    "editor.foreground": "#cccac2ff",
    "editor.background": "#242835ff",
    "editor.gutter.background": "#242835ff",
    "terminal.background": "#242835ff",
    "terminal.foreground": "#cccac2ff",
    "syntax.comment": "#b8cfe68c",
    "syntax.keyword": "#ffad65ff",
    "syntax.string": "#d4fe7fff",
    "syntax.number": "#dfbfffff",
    "syntax.type": "#73cfffff",
    "syntax.function": "#ffd173ff",
    "syntax.method": "#ffd173ff",
    "syntax.class": "#72cfffff",
    "syntax.interface": "#73cfffff",
    "syntax.variable": "#cccac2ff",
    "syntax.parameter": "#cccac2ff",
    "syntax.property": "#72cfffff",
    "syntax.constant": "#dfbfffff",
    "syntax.operator": "#f29e74ff",
    "syntax.bracket": "#b4b3aeff",
    "syntax.import": "#ffad65ff",
    "syntax.tag": "#72cfffff",
    "syntax.attribute": "#72cfffff",
  },
  syntax: ayuSyntaxByThemeId["ayu-mirage"],
  monacoColors: {
    "editor.lineHighlightBackground": "#353944bf",
    "editor.selectionBackground": "#72cffe3d",
    "editor.inactiveSelectionBackground": "#72cffe1a",
    "editor.findMatchBackground": "#73cffe66",
    "editor.findMatchHighlightBackground": "#73cffe66",
    "editorLineNumber.foreground": "#cccac259",
    "editorLineNumber.activeForeground": "#cccac2ff",
    "editorCursor.foreground": "#72cfffff",
    "editorIndentGuide.background1": "#cccac20d",
    "editorIndentGuide.activeBackground1": "#cccac21a",
    "editorBracketMatch.background": "#72cffe1a",
    "editorBracketMatch.border": "#72cfffff",
    "scrollbarSlider.background": "#cccac24c",
    "scrollbarSlider.hoverBackground": "#43464fff",
    "scrollbarSlider.activeBackground": "#53565dff",
    "editorWidget.background": "#353944ff",
    "editorWidget.border": "#43464fff",
    "editorSuggestWidget.background": "#353944ff",
    "editorSuggestWidget.border": "#43464fff",
    "editorSuggestWidget.selectedBackground": "#53565dff",
    "editorSuggestWidget.highlightForeground": "#72cfffff",
    focusBorder: "#24556fff",
  },
});
