import { createAxonThemeImport } from "./axonThemeImport";

export const oneThemes = [
  createAxonThemeImport({
    id: "one-dark",
    label: "One Dark",
    appearance: "dark",
    tokens: {
          "background": "#3b414dff",
          "status_bar.background": "#3b414dff",
          "title_bar.background": "#3b414dff",
          "toolbar.background": "#282c33ff",
          "sidebar.background": "#2f343eff",
          "sidebar.hover_background": "#363c46ff",
          "sidebar.border": "#464b57ff",
          "tab.active_background": "#282c33ff",
          "panel.background": "#2f343eff",
          "panel.border": "#464b57ff",
          "panel.overlay_hover": "#363c46ff",
          "editor.foreground": "#acb2beff",
          "editor.background": "#282c33ff",
          "editor.gutter.background": "#282c33ff",
          "terminal.background": "#282c33ff",
          "terminal.foreground": "#c8ccd4ff",
          "syntax.comment": "#5d636fff",
          "syntax.keyword": "#b477cfff",
          "syntax.string": "#a1c181ff",
          "syntax.number": "#bf956aff",
          "syntax.type": "#6eb4bfff",
          "syntax.function": "#73ade9ff",
          "syntax.method": "#73ade9ff",
          "syntax.class": "#73ade9ff",
          "syntax.interface": "#6eb4bfff",
          "syntax.variable": "#c8ccd4ff",
          "syntax.parameter": "#c8ccd4ff",
          "syntax.property": "#d07277ff",
          "syntax.constant": "#dfc184ff",
          "syntax.operator": "#6eb4bfff",
          "syntax.bracket": "#acb2beff",
          "syntax.import": "#b477cfff",
          "syntax.tag": "#74ade8ff",
          "syntax.attribute": "#74ade8ff"
    },
    monacoColors: {
          "editor.lineHighlightBackground": "#2f343ebf",
          "editor.selectionBackground": "#74ade83d",
          "editor.inactiveSelectionBackground": "#74ade83d",
          "editor.findMatchBackground": "#74ade866",
          "editor.findMatchHighlightBackground": "#74ade866",
          "editorLineNumber.foreground": "#c8ccd459",
          "editorLineNumber.activeForeground": "#c8ccd4ff",
          "editorCursor.foreground": "#74ade8ff",
          "editorIndentGuide.background1": "#c8ccd40d",
          "editorIndentGuide.activeBackground1": "#c8ccd41a",
          "editorBracketMatch.background": "#74ade81a",
          "editorBracketMatch.border": "#293b5bff",
          "scrollbarSlider.background": "#c8ccd44c",
          "scrollbarSlider.hoverBackground": "#363c46ff",
          "scrollbarSlider.activeBackground": "#454a56ff",
          "editorWidget.background": "#2f343eff",
          "editorWidget.border": "#464b57ff",
          "editorSuggestWidget.background": "#2f343eff",
          "editorSuggestWidget.border": "#464b57ff",
          "editorSuggestWidget.selectedBackground": "#454a56ff",
          "editorSuggestWidget.highlightForeground": "#74ade8ff",
          "focusBorder": "#293b5bff"
    },
  }),
  createAxonThemeImport({
    id: "one-light",
    label: "One Light",
    appearance: "light",
    tokens: {
          "background": "#dcdcddff",
          "status_bar.background": "#dcdcddff",
          "title_bar.background": "#dcdcddff",
          "toolbar.background": "#fafafaff",
          "sidebar.background": "#ebebecff",
          "sidebar.hover_background": "#dfdfe0ff",
          "sidebar.border": "#c9c9caff",
          "tab.active_background": "#fafafaff",
          "panel.background": "#ebebecff",
          "panel.border": "#c9c9caff",
          "panel.overlay_hover": "#dfdfe0ff",
          "editor.foreground": "#383a41ff",
          "editor.background": "#fafafaff",
          "editor.gutter.background": "#fafafaff",
          "terminal.background": "#fafafaff",
          "terminal.foreground": "#383a41ff",
          "syntax.comment": "#a2a3a7ff",
          "syntax.keyword": "#a449abff",
          "syntax.string": "#649f57ff",
          "syntax.number": "#ad6e25ff",
          "syntax.type": "#3882b7ff",
          "syntax.function": "#5b79e3ff",
          "syntax.method": "#5b79e3ff",
          "syntax.class": "#5c78e2ff",
          "syntax.interface": "#3882b7ff",
          "syntax.variable": "#383a41ff",
          "syntax.parameter": "#383a41ff",
          "syntax.property": "#d3604fff",
          "syntax.constant": "#669f59ff",
          "syntax.operator": "#3882b7ff",
          "syntax.bracket": "#383a41ff",
          "syntax.import": "#a449abff",
          "syntax.tag": "#5c78e2ff",
          "syntax.attribute": "#5c78e2ff"
    },
    monacoColors: {
          "editor.lineHighlightBackground": "#ebebecbf",
          "editor.selectionBackground": "#5c78e23d",
          "editor.inactiveSelectionBackground": "#5c78e23d",
          "editor.findMatchBackground": "#5c79e266",
          "editor.findMatchHighlightBackground": "#5c79e266",
          "editorLineNumber.foreground": "#383a4159",
          "editorLineNumber.activeForeground": "#383a41ff",
          "editorCursor.foreground": "#5c78e2ff",
          "editorIndentGuide.background1": "#383a410d",
          "editorIndentGuide.activeBackground1": "#383a411a",
          "editorBracketMatch.background": "#5c78e21a",
          "editorBracketMatch.border": "#cbcdf6ff",
          "scrollbarSlider.background": "#383a414c",
          "scrollbarSlider.hoverBackground": "#dfdfe0ff",
          "scrollbarSlider.activeBackground": "#cacacaff",
          "editorWidget.background": "#ebebecff",
          "editorWidget.border": "#c9c9caff",
          "editorSuggestWidget.background": "#ebebecff",
          "editorSuggestWidget.border": "#c9c9caff",
          "editorSuggestWidget.selectedBackground": "#cacacaff",
          "editorSuggestWidget.highlightForeground": "#5c78e2ff",
          "focusBorder": "#cbcdf6ff"
    },
  }),
];
