import { createAxonThemeImport } from "./axonThemeImport";

export const solarizedThemes = [
  createAxonThemeImport({
    id: "solarized-dark",
    label: "Solarized Dark",
    appearance: "dark",
    tokens: {
          "background": "#073743ff",
          "status_bar.background": "#073743ff",
          "title_bar.background": "#073743ff",
          "toolbar.background": "#002a35ff",
          "sidebar.background": "#04313bff",
          "sidebar.hover_background": "#053541ff",
          "sidebar.border": "#2b4e58ff",
          "tab.active_background": "#002a35ff",
          "panel.background": "#04313bff",
          "panel.border": "#2b4e58ff",
          "panel.overlay_hover": "#053541ff",
          "editor.foreground": "#fdf6e3ff",
          "editor.background": "#002a35ff",
          "editor.gutter.background": "#002a35ff",
          "terminal.background": "#002a35ff",
          "terminal.foreground": "#fdf6e3ff",
          "syntax.comment": "#99a5a4ff",
          "syntax.keyword": "#278ad1ff",
          "syntax.string": "#cb4b16ff",
          "syntax.number": "#849903ff",
          "syntax.type": "#2ba198ff",
          "syntax.function": "#b58902ff",
          "syntax.method": "#b58902ff",
          "syntax.class": "#278ad1ff",
          "syntax.interface": "#2ba198ff",
          "syntax.variable": "#fdf6e3ff",
          "syntax.parameter": "#fdf6e3ff",
          "syntax.property": "#278ad1ff",
          "syntax.constant": "#849903ff",
          "syntax.operator": "#cb4b16ff",
          "syntax.bracket": "#efe9d6ff",
          "syntax.import": "#278ad1ff",
          "syntax.tag": "#278ad1ff",
          "syntax.attribute": "#278ad1ff"
    },
    monacoColors: {
          "editor.lineHighlightBackground": "#04313bbf",
          "editor.selectionBackground": "#278ad13d",
          "editor.inactiveSelectionBackground": "#278ad13d",
          "editor.findMatchBackground": "#288bd166",
          "editor.findMatchHighlightBackground": "#288bd166",
          "editorLineNumber.foreground": "#fdf6e359",
          "editorLineNumber.activeForeground": "#fdf6e3ff",
          "editorCursor.foreground": "#278ad1ff",
          "editorIndentGuide.background1": "#fdf6e30d",
          "editorIndentGuide.activeBackground1": "#fdf6e31a",
          "editorBracketMatch.background": "#278ad11a",
          "editorBracketMatch.border": "#1b3149ff",
          "scrollbarSlider.background": "#fdf6e34c",
          "scrollbarSlider.hoverBackground": "#053541ff",
          "scrollbarSlider.activeBackground": "#294d58ff",
          "editorWidget.background": "#04313bff",
          "editorWidget.border": "#2b4e58ff",
          "editorSuggestWidget.background": "#04313bff",
          "editorSuggestWidget.border": "#2b4e58ff",
          "editorSuggestWidget.selectedBackground": "#294d58ff",
          "editorSuggestWidget.highlightForeground": "#278ad1ff",
          "focusBorder": "#1b3149ff"
    },
  }),
  createAxonThemeImport({
    id: "solarized-light",
    label: "Solarized Light",
    appearance: "light",
    tokens: {
          "background": "#cfd0c4ff",
          "status_bar.background": "#cfd0c4ff",
          "title_bar.background": "#cfd0c4ff",
          "toolbar.background": "#fdf6e3ff",
          "sidebar.background": "#f3eddaff",
          "sidebar.hover_background": "#dcdacbff",
          "sidebar.border": "#9faaa8ff",
          "tab.active_background": "#fdf6e3ff",
          "panel.background": "#f3eddaff",
          "panel.border": "#9faaa8ff",
          "panel.overlay_hover": "#dcdacbff",
          "editor.foreground": "#002a35ff",
          "editor.background": "#fdf6e3ff",
          "editor.gutter.background": "#fdf6e3ff",
          "terminal.background": "#fdf6e3ff",
          "terminal.foreground": "#002a35ff",
          "syntax.comment": "#30525bff",
          "syntax.keyword": "#288bd1ff",
          "syntax.string": "#cb4b17ff",
          "syntax.number": "#849903ff",
          "syntax.type": "#2ba198ff",
          "syntax.function": "#b58903ff",
          "syntax.method": "#b58903ff",
          "syntax.class": "#288bd1ff",
          "syntax.interface": "#2ba198ff",
          "syntax.variable": "#002a35ff",
          "syntax.parameter": "#002a35ff",
          "syntax.property": "#288bd1ff",
          "syntax.constant": "#849903ff",
          "syntax.operator": "#cb4b17ff",
          "syntax.bracket": "#04333eff",
          "syntax.import": "#288bd1ff",
          "syntax.tag": "#288bd1ff",
          "syntax.attribute": "#288bd1ff"
    },
    monacoColors: {
          "editor.lineHighlightBackground": "#f3eddabf",
          "editor.selectionBackground": "#288bd13d",
          "editor.inactiveSelectionBackground": "#288bd13d",
          "editor.findMatchBackground": "#298bd166",
          "editor.findMatchHighlightBackground": "#298bd166",
          "editorLineNumber.foreground": "#002a3559",
          "editorLineNumber.activeForeground": "#002a35ff",
          "editorCursor.foreground": "#288bd1ff",
          "editorIndentGuide.background1": "#002a350d",
          "editorIndentGuide.activeBackground1": "#002a351a",
          "editorBracketMatch.background": "#288bd11a",
          "editorBracketMatch.border": "#bfd3efff",
          "scrollbarSlider.background": "#002a354c",
          "scrollbarSlider.hoverBackground": "#dcdacbff",
          "scrollbarSlider.activeBackground": "#a2aca9ff",
          "editorWidget.background": "#f3eddaff",
          "editorWidget.border": "#9faaa8ff",
          "editorSuggestWidget.background": "#f3eddaff",
          "editorSuggestWidget.border": "#9faaa8ff",
          "editorSuggestWidget.selectedBackground": "#a2aca9ff",
          "editorSuggestWidget.highlightForeground": "#288bd1ff",
          "focusBorder": "#bfd3efff"
    },
  }),
];
