export const AXON_COMMANDS = {
  ABOUT: "about",
  NEW_FILE: "new-file",
  OPEN_FOLDER: "open-folder",
  OPEN_RECENT: "open-recent",
  SAVE: "save",
  SAVE_AS: "save-as",
  CLOSE_TAB: "close-tab",
  OPEN_COMMAND_PALETTE: "open-command-palette",
  OPEN_WORKSPACE_OVERVIEW: "open-workspace-overview",
  OPEN_WORKSPACE_SEARCH: "open-workspace-search",
  OPEN_PROBLEMS_PANEL: "open-problems-panel",
  OPEN_OUTPUT_PANEL: "open-output-panel",
  REFRESH_DIAGNOSTICS: "refresh-diagnostics",
  NEXT_PROBLEM: "next-problem",
  PREVIOUS_PROBLEM: "previous-problem",
  CLEAR_OUTPUT: "clear-output",
  OPEN_DIFF_VIEW: "open-diff-view",
  OPEN_SOURCE_CONTROL: "open-source-control",
  OPEN_GIT_HISTORY: "open-git-history",
  OPEN_SPOTIFY: "open-spotify",
  OPEN_TASK_RUNNER: "open-task-runner",
  OPEN_TEST_EXPLORER: "open-test-explorer",
  OPEN_DEBUGGER: "open-debugger",
  OPEN_FILE_OUTLINE: "open-file-outline",
  OPEN_LANGUAGE_TOOLS: "open-language-tools",
  INSPECT_EDITOR_TOKEN: "inspect-editor-token",
  GO_TO_DEFINITION: "go-to-definition",
  FIND_REFERENCES: "find-references",
  RENAME_SYMBOL: "rename-symbol",
  FORMAT_DOCUMENT: "format-document",
  OPEN_CODE_SNAPSHOT: "open-code-snapshot",
  OPEN_HTML_PREVIEW: "open-html-preview",
  TOGGLE_TERMINAL: "toggle-terminal",
  OPEN_SETTINGS: "open-settings",
  OPEN_EXTENSIONS: "open-extensions",
  OPEN_SETTINGS_JSON: "open-settings-json",
  OPEN_UPDATE_NOTES: "open-update-notes",
  TOGGLE_ZEN_MODE: "toggle-zen-mode",
  NEW_TERMINAL: "new-terminal",
  ASK_AXON: "ask-axon",
  AI_EXPLAIN_SELECTION: "ai-explain-selection",
  AI_FIX_PROBLEM: "ai-fix-problem",
  AI_REFACTOR_SELECTION: "ai-refactor-selection",
  AI_GENERATE_TESTS: "ai-generate-tests",
  AI_REVIEW_GIT_DIFF: "ai-review-git-diff",
  AI_DRAFT_COMMIT_MESSAGE: "ai-draft-commit-message",
} as const;

export type BuiltInAxonCommand =
  (typeof AXON_COMMANDS)[keyof typeof AXON_COMMANDS];
export type ExtensionAxonCommand = `extension:${string}`;
export type AxonCommand = BuiltInAxonCommand | ExtensionAxonCommand;
