import { type AxonThemeDefinition } from "./types";
import {
  moonlightMonacoColors,
  moonlightSemanticTokenColors,
  moonlightTokenRules,
} from "./axonMoonlightData";

export const axonMoonlightTheme: AxonThemeDefinition = {
  id: "axon-moonlight",
  label: "Axon Moonlight",
  base: "vs-dark",
  tokens: {
    background: "#1e2030",
    "status_bar.background": "#1e2030",
    "title_bar.background": "#1e2030",
    "toolbar.background": "#1e2030",
    "sidebar.background": "#1e2030",
    "sidebar.border": "#191a2a",
    "tab.active_background": "#222436",
    "panel.background": "#1e2030",
    "panel.border": "#00000033",
    "panel.overlay_hover": "#222436",
    "editor.foreground": "#c8d3f5",
    "editor.background": "#222436",
    "editor.gutter.background": "#222436",
    "terminal.background": "#1e2030",
    "terminal.foreground": "#d5def8",
    "syntax.comment": "#7a88cf",
    "syntax.keyword": "#c4a2ff",
    "syntax.string": "#c3e88d",
    "syntax.number": "#ff966c",
    "syntax.type": "#3ad7c7",
    "syntax.function": "#7cafff",
    "syntax.method": "#60bdff",
    "syntax.class": "#ffc777",
    "syntax.interface": "#3ad7c7",
    "syntax.variable": "#c8d3f5",
    "syntax.parameter": "#fca7ea",
    "syntax.property": "#a9b8e8",
    "syntax.constant": "#ff98a4",
    "syntax.operator": "#78dbff",
    "syntax.bracket": "#a9b8e8",
    "syntax.import": "#c8d3f5",
    "syntax.tag": "#ff757f",
    "syntax.attribute": "#c4a2ff",
  },
  monacoColors: moonlightMonacoColors,
  tokenRules: moonlightTokenRules,
  semanticTokenColors: moonlightSemanticTokenColors,
};
