import { type AxonThemeDefinition } from "./types";

export const ayuDarkTheme: AxonThemeDefinition = {
  id: "ayu-dark",
  label: "Ayu Dark",
  base: "vs-dark",
  tokens: {
    background: "#0b0e14",
    "status_bar.background": "#080b10",
    "title_bar.background": "#080b10",
    "toolbar.background": "#080b10",
    "sidebar.background": "#080b10",
    "sidebar.border": "#1f2430",
    "tab.active_background": "#11151c",
    "panel.background": "#080b10",
    "panel.border": "#1f2430",
    "panel.overlay_hover": "#11151c",
    "editor.foreground": "#b3b1ad",
    "editor.background": "#0b0e14",
    "editor.gutter.background": "#0b0e14",
    "terminal.background": "#0b0e14",
    "terminal.foreground": "#c8d0e0",
    "syntax.comment": "#5c6773",
    "syntax.keyword": "#ff8f40",
    "syntax.string": "#aad94c",
    "syntax.number": "#d2a6ff",
    "syntax.type": "#ffb454",
    "syntax.function": "#ffd580",
    "syntax.method": "#ffd580",
    "syntax.class": "#ffb454",
    "syntax.interface": "#ffb454",
    "syntax.variable": "#b3b1ad",
    "syntax.parameter": "#f29668",
    "syntax.property": "#73d0ff",
    "syntax.constant": "#d2a6ff",
    "syntax.operator": "#f29668",
    "syntax.bracket": "#b3b1ad",
    "syntax.import": "#ff8f40",
    "syntax.tag": "#5ccfe6",
    "syntax.attribute": "#ffb454",
  },
  monacoColors: {
    "editor.lineHighlightBackground": "#11151c",
    "editor.selectionBackground": "#273747",
    "editor.inactiveSelectionBackground": "#27374780",
    "editor.findMatchBackground": "#32516f",
    "editor.findMatchHighlightBackground": "#32516f80",
    "editorLineNumber.foreground": "#3d424d",
    "editorLineNumber.activeForeground": "#ffb454",
    "editorCursor.foreground": "#ffcc66",
    "editorIndentGuide.background1": "#1f2430",
    "editorIndentGuide.activeBackground1": "#3d424d",
    "editorBracketMatch.background": "#27374780",
    "editorBracketMatch.border": "#ffb454",
    "scrollbarSlider.background": "#3d424d66",
    "scrollbarSlider.hoverBackground": "#3d424d99",
    "scrollbarSlider.activeBackground": "#5c6773",
    "editorWidget.background": "#11151c",
    "editorWidget.border": "#1f2430",
    "editorSuggestWidget.background": "#11151c",
    "editorSuggestWidget.border": "#1f2430",
    "editorSuggestWidget.selectedBackground": "#1f2430",
    "editorSuggestWidget.highlightForeground": "#ffb454",
    focusBorder: "#ffb454",
  },
};
